name: Node Continuous Integration

on: 
  pull_request:
    branches: [master]

jobs:
  test_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - run: cd client && npm ci && npm test